### ISSUE TITLE
failed to set context data, res->status = 5; (null)

### ISSUE THREAD

**Issue by petsuter** [workflowproducts/postage#336] opened 2017-07-30 08:50 UTC
I get this error when starting the application and connecting to the DB:

![postageerror5](https://user-images.githubusercontent.com/8830354/28751970-a3b9aeea-7514-11e7-9f38-8fad58115b4c.png)

Same error happens again after clicking "Reload Postage".

Postage.Windows.3.2.16 release, Postgres 9.0, Windows 10.

**Comment by MarHoff** [comment] 2017-07-30 09:28
Not a dev just passing by, but the big red text "You are on an unsupported version of Postgres" look like a good hint have you checked all the requirements ?

**Comment by petsuter** [comment] 2017-07-30 12:06
I must have overlooked that. Would be nice to include it in the actual  error message.

Also I didn't see any requirements or a list  of compatible version anywhere.

**Comment by nunziotocci** [comment] 2017-07-31 18:06
I have determined that the problem isn't directly related to 9.0 being discontinued.

It seems that 9.2 was the release that allowed *all* custom runtime-configuration variables regardless of the postgresql.conf.

As a temporary fix, you can add this to your postgresql configuration:
```
custom_variable_classes = 'sunny'
```

I will disable the context data for Postage because it isn't actually used (it's meant for Envelope).

**Comment by justintocci** [comment] 2017-07-31 18:38
So we're just going to disable this option in postage right?

**Comment by nunziotocci** [comment] 2017-07-31 18:42
Yes, we won't be setting the context data in Postage anymore.

**Comment by nunziotocci** [comment] 2017-07-31 18:44
Fixed in 558ebc09e82eabdd948ff43ec49a0e473debe657

**Closed by nunziotocci** 2017-07-31 18:44 UTC

**Comment by MarHoff** [comment] 2017-08-01 08:15
Again just passing by but whished to say... awesome support !
