### ISSUE TITLE
Dump schema doesn't handle types

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#135] opened 2017-03-04 21:01 UTC
This line failed in my dump script because the type wasn't in the script.

![screen shot 2017-03-04 at 2 46 39 pm](https://cloud.githubusercontent.com/assets/14278246/23582223/54b0f0a8-00eb-11e7-9a90-5be307241aee.png)

**Comment by justintocci** [comment] 2017-03-04 21:29
Actually, I think TYPEs are already handled by Postage in all cases. I did a psql

\dT
and then 
\dT+

Both commands returned no TYPE definitions. Postage displays the TYPE no problem though. Next I did

\set ECHO_HIDDEN on

That turns on the SQL when you run your \d commands. I got the following query:

```
SELECT n.nspname as "Schema",
  pg_catalog.format_type(t.oid, NULL) AS "Name",
  t.typname AS "Internal name",
  CASE WHEN t.typrelid != 0
      THEN CAST('tuple' AS pg_catalog.text)
    WHEN t.typlen < 0
      THEN CAST('var' AS pg_catalog.text)
    ELSE CAST(t.typlen AS pg_catalog.text)
  END AS "Size",
  pg_catalog.array_to_string(
      ARRAY(
		     SELECT e.enumlabel
          FROM pg_catalog.pg_enum e
          WHERE e.enumtypid = t.oid
          ORDER BY e.enumsortorder
      ),
      E'\n'
  ) AS "Elements",
pg_catalog.array_to_string(t.typacl, E'\n') AS "Access privileges",
    pg_catalog.obj_description(t.oid, 'pg_type') as "Description"
FROM pg_catalog.pg_type t
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
WHERE (t.typrelid = 0 OR (SELECT c.relkind = 'c' FROM pg_catalog.pg_class c WHERE c.oid = t.typrelid))
  AND NOT EXISTS(SELECT 1 FROM pg_catalog.pg_type el WHERE el.oid = t.typelem AND el.typarray = t.oid)
      AND n.nspname <> 'pg_catalog'
      AND n.nspname <> 'information_schema'
  AND pg_catalog.pg_type_is_visible(t.oid)
ORDER BY 1, 2;
```

Commenting out this line is what fixed the query to show our TYPEs:

-- AND pg_catalog.pg_type_is_visible(t.oid)

I have no idea why that line is there at all. The related documentation is here: https://www.postgresql.org/docs/9.4/static/functions-info.html#FUNCTIONS-INFO-SCHEMA-TABLE

I have to assume we have that line in our dump script code. Removing it should fix the problem.

**Comment by nunziotocci** [comment] 2017-03-04 21:37
@justintocci Actually, we aren't using that query. The problem is that we are completely ignoring the types in the surgery.

I will add types and also check if any other objects are missing.

**Comment by nunziotocci** [comment] 2017-03-04 23:33
Fixed in the next release.

**Closed by nunziotocci** 2017-03-04 23:33 UTC
