### ISSUE TITLE
Ace Dollar tag syntax highlighting

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#274] opened 2017-05-27 16:05 UTC
Currently ace only highlights the contents of a dollar tag if the dollar tag starts at the beginning of a line.
It would be much more useful if instead it checked if the first character was a return.

**Comment by crosstocci** [comment] 2017-06-05 19:32
Could not reproduce.

**Comment by justintocci** [comment] 2017-06-05 19:54
Inside a FUNCTION, inside a $BODY$ tag, I may want to do something like this:

```
str_sql := $x$ SELECT * FROM ok; $x$;
```
 
But if I do that, the query is all blue. I would like it to be syntax highlighted instead.

I can work around the issue for now by doing:

```
str_sql := 
$x$
  SELECT * FROM ok; 
$x$;
```
I'm wondering if it would be ok to make it so that if the first character in a dollar tag is a RETURN, then give me syntax highlighting. If not, then make it blue. This would let me at least indent the SQL so it looks nicer:

```
str_sql := $x$
      SELECT * FROM ok; 
      $x$;
```

**Comment by justintocci** [comment] 2017-06-23 16:56
Ok, maybe that is too hard. Could we make it so that $BODY$ tags are always syntax highlighted and $ANYTHING_ELSE$ is blue?

**Comment by crosstocci** [comment] 2017-07-05 19:32
Fixed in next release.

**Comment by justintocci** [comment] 2017-07-15 19:39
Dollar tag highlighting is all messed up. Look at the following image and you'll see that $$ tags no longer cause the string to be blue. They are black instead.

![screen shot 2017-07-15 at 2 37 42 pm](https://user-images.githubusercontent.com/14250339/28242214-52847e42-696b-11e7-9f7b-d64b191d0819.JPG)

**Comment by justintocci** [comment] 2017-07-15 19:43
next i tried to change a double dollar ($$) to a dollar tag ($SQL$) and when I typed $sql$ i could no longer use the arrow keys. Not sure how that even happened. 

For the record, it also refused to color the string either way. It could have made it blue or let the syntax highlighting work but instead it was just all black again.

**Comment by crosstocci** [comment] 2017-07-17 19:03
Fixed in next release.

Checked with @justintocci to see if we could reproduce arrow key problem, unable to reproduce.

**Closed by crosstocci** 2017-07-17 19:03 UTC
Labels: enhancement
