### ISSUE TITLE
Tree view shows one view, but there are none under it

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#290] opened 2017-05-31 18:36 UTC
![screen shot 2017-05-31 at 1 35 25 pm](https://cloud.githubusercontent.com/assets/14278246/26647793/16a118d2-4606-11e7-86c3-9787970fd0b4.png)

**Comment by crosstocci** [comment] 2017-05-31 18:56
This a duplicate of #282, an issue that was already fixed.

I have confirmed this.

**Closed by crosstocci** 2017-05-31 18:56 UTC
