### ISSUE TITLE
Add a button to the SQL File view for "AutoCommit"

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#14] opened 2016-09-30 18:40 UTC
When Autocommit is on, have it run the query like this:

commit; 

\<query\>

begin;

This will allow people to do vacuum operations from a SQL File. 

Turn the button red when its on.

Also, make the float cursor say "AutoCommit" or something appropriate.

**Comment by crosstocci** [comment] 2017-03-04 23:39
Duplicate of #124

**Closed by crosstocci** 2017-03-04 23:39 UTC
Labels: enhancement
