### ISSUE TITLE
PostgresApp compatibility

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#94] opened 2017-01-02 14:39 UTC
Moved from PostgresApp/PostgresApp/issues/365

**Comment by nunziotocci** [comment] 2017-01-02 14:41
@chrispysoft, please send me the output of `ps -ef | grep -i post`

**Comment by chrispysoft** [comment] 2017-01-02 14:45
MacBook-Pro-TB:~ chris$ ps -ef | grep -i post
  501   426     1   0 12:22PM ??         0:00.93 /Applications/Postgres.app/Contents/MacOS/PostgresMenuHelper.app/Contents/MacOS/PostgresMenuHelper
  501  2506     1   0  1:13PM ??         0:00.22 /Applications/Postgres.app/Contents/Versions/9.6/bin/postgres -D /Users/chris/Library/Application Support/Postgres/var-9.6 -p 5432
  501  2508  2506   0  1:13PM ??         0:00.05 postgres: checkpointer process       
  501  2509  2506   0  1:13PM ??         0:00.11 postgres: writer process       
  501  2510  2506   0  1:13PM ??         0:00.09 postgres: wal writer process       
  501  2511  2506   0  1:13PM ??         0:00.17 postgres: autovacuum launcher process       
  501  2512  2506   0  1:13PM ??         0:00.70 postgres: stats collector process       
  501  4272  4274   0  3:35PM ??         0:08.79 /Users/chris/Library/Developer/Xcode/DerivedData/Postico-dqftdemvgkharzfeobxadzivncvy/Build/Products/Debug/Postico.app/Contents/MacOS/Postico -NSDocumentRevisionsDebugMode YES
  501  4280  2506   0  3:35PM ??         0:00.04 postgres: chris chris ::1(50342) idle    
  501  4333     1   0  3:42PM ??         0:01.16 /Applications/Postage.app/Contents/MacOS/Postage
  501  4334  4333   0  3:42PM ??         0:00.27 /Applications/Postage.app/Contents/Frameworks/Postage Helper.app/Contents/MacOS/Postage Helper --type=gpu-process --channel=4333.0.1862529762 --mojo-application-channel-token=0F41950E0E5F752FA723755A11B2CD3B --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=18,20,29,40,48,51,52,56,58,66,67,71,73,75 --gpu-vendor-id=0x8086 --gpu-device-id=0x1927 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x1927
  501  4335  4333   0  3:42PM ??         0:00.01 /Applications/Postage.app/Contents/Resources/app/postage/postage -c /Users/chris/.postage/postage.conf -d /Users/chris/.postage/postage-connections.conf -r /Applications/Postage.app/Contents/Resources/app/postage/web_root -x t -p 44988
  501  4336  4333   0  3:42PM ??         0:01.21 /Applications/Postage.app/Contents/Frameworks/Postage Helper.app/Contents/MacOS/Postage Helper --type=renderer --no-sandbox --primordial-pipe-token=E715D699094C8F95F60117728F17B1F8 --lang=en-GB --node-integration=true --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=F37B5695409237D59997B644EFBA4117 --mojo-application-channel-token=E715D699094C8F95F60117728F17B1F8 --channel=4333.1.1998715794
  501  4364  4357   0  3:42PM ttys003    0:00.00 grep -i post

**Comment by nunziotocci** [comment] 2017-01-02 14:49
Thanks, I am going to install 10.12 and test this. I can't seem to replicate it on 10.11.6.

**Comment by chrispysoft** [comment] 2017-01-02 14:52
OK. Please mind that I'm using a brand new mac with a clean install of macOS 10.12.

**Comment by justintocci** [comment] 2017-01-02 20:31
I upgraded to Sierra. Postage had a little delay in the Icon showing up in the dock, but it didn't create an issue. Once I started Postage I was able to log right in.

Then I created a Sierra virtual machine in VMWare Fusion. I tried to log in to an SSL postgresql instance and got an error. The error appears in the page, below the login button. 

```
cannot start connect: sslmode value "require" invalid when SSL support is not compiled in
```

The error is because the Apple libpq that ships with Sierra doesn't have SSL capability. It would seem that the main thing for us to do here is to make the error go to a popup so that people can see that there is in fact an error and the problem is not with Postage. I suspect that your screen was simply too small to show the error. This was a bad idea on our part and will be fixed. 

Chrispysoft, please refer to [our readme on LibPQ](https://github.com/workflowproducts/postage/blob/master/INSTALL_LIBPQ.md). Feel free to post here if that document is inadequate. We'll help you fix your issue and then update the document. 

If we've misdiagnosed your error please let us know. Here is a screen shot of the error:
![screen shot 2017-01-02 at 2 28 00 pm](https://cloud.githubusercontent.com/assets/14250339/21595812/b051f304-d0f7-11e6-8913-34e7b27fbe9c.JPG)

**Comment by justintocci** [comment] 2017-01-02 20:37
I forgot to mention above, I did try to connect to a PostgreSQL instance that didn't require SSL and it logged right in.

**Comment by justintocci** [comment] 2017-01-02 21:41
So Apple apparently [requires developers to include libraries such as LibPQ in their applications now] (https://forums.developer.apple.com/thread/65619)

Long ago we set LibPQ as a dependency in the Electron versions of Postage for Windows and Linux but we never did that for Mac. We'll add LibPQ to the Electron version of Postage for Mac and this SSL issue will go away.

**Comment by michaeltocci** [comment] 2017-01-05 16:58
I've made it so that when a login error occurs, there is now a popup. The changes will be seen in the next release.

**Closed by michaeltocci** 2017-01-05 16:58 UTC
